[FeAmGen]
git-tree-sha1 = "ca5d522c4bec49202b62e1f895539bf934b97a68"

    [[FeAmGen.download]]
    url = "https://raw.githubusercontent.com/zhaoli-IHEP/FeAmGen_artifacts/main/utils.tar.gz"
    sha256 = "911e5eb4293a77af0b417057624a6eddbd0fdbcac0595c4ca3a8bfbef850a738"
