[FeAmGen]
git-tree-sha1 = "448154f0868862ec339771a3963ac4dbf1e18685"

    [[FeAmGen.download]]
    url = "https://raw.githubusercontent.com/zhaoli-IHEP/FeAmGen_artifacts/main/utils.tar.gz"
    sha256 = "64714486b9b7e5ede22ea5e01c22994babce9c34bdc1beacba87ac8b48842bdd"
